backend = "glx"

opacity-rule = 0.95

#blur-background = true
#blur-method = "dual_kawase"
#blur-strength = 4

rounded-corners = true
corner-radius = 0
rounded-corners-exclude = [
    "window_type = 'dock'"
]

fading = true
fade-in-step = 0.05
fade-out-step = 0.05
