order += "volume master"
order += "wireless wlp2s0"
order += "battery 0"
order += "cpu_temperature 0"
order += "cpu_usage 0"
order += "load"
order += "tztime local"

wireless wlp4s0 {
    format_up = "%quality  %essid %ip"
    format_down = ""
}

battery 0 {
    format = "%status %percentage"
    format_down = ""
    last_full_capacity = true
    integer_battery_capacity = true
    low_threshold = 11
    threshold_type = percentage
    hide_seconds = true
    status_chr = " "
    status_bat = " "
    status_unk = " "
    status_full = " "
}

tztime local {
    format = "%V  %A %e.%B   %I:%M%p"
}

load {
    format = " %1min"
}

cpu_usage {
    format = " %usage"
}

cpu_temperature 0 {
	format = " %degrees°C"
}

volume master {
    format = "%volume  "
    format_muted = " "
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}
